# Generated by Django 5.2.14 on 2026-06-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('Office', models.CharField(max_length=100)),
                ('Age', models.IntegerField(max_length=3)),
                ('Start_Date', models.DateField()),
                ('Salary', models.IntegerField(max_length=10)),
            ],
        ),
    ]
