# Generated by Django 5.2.14 on 2026-06-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddEmployee',
            new_name='Employees',
        ),
    ]
